### ISSUE TITLE
Crash when opening settings

### ISSUE THREAD

**Issue by bushrang3r** [otakuhqz/ZimLX#9] opened 2019-02-06 14:02 UTC
Sorry! It's long!

Build version: 0.4.4 
Build date: 1980-01-01 00:00:00 
Current date: 2019-02-06 22:59:55 
Device: Samsung SM-A3000 
 
Stack trace:  
android.content.res.Resources$NotFoundException: File res/drawable/ic_style.xml from drawable resource ID #0x7f0800b8
	at android.content.res.Resources.loadDrawableForCookie(Resources.java:2890)
	at android.content.res.Resources.loadDrawable(Resources.java:2765)
	at android.content.res.Resources.getDrawable(Resources.java:1012)
	at android.content.Context.getDrawable(Context.java:402)
	at android.support.v4.content.ContextCompat.getDrawable(ContextCompat.java:358)
	at android.support.v7.preference.Preference.onBindViewHolder(Preference.java:591)
	at org.zimmob.zimlx.settings.ui.SubPreference.onBindViewHolder(SubPreference.java:45)
	at android.support.v7.preference.PreferenceGroupAdapter.onBindViewHolder(PreferenceGroupAdapter.java:362)
	at android.support.v7.preference.PreferenceGroupAdapter.onBindViewHolder(PreferenceGroupAdapter.java:43)
	at android.support.v7.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:6508)
	at android.support.v7.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:6541)
	at android.support.v7.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:5484)
	at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5750)
	at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5589)
	at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5585)
	at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2231)
	at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1558)
	at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1518)
	at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:610)
	at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3719)
	at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3436)
	at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3988)
	at android.view.View.layout(View.java:15992)
	at android.view.ViewGroup.layout(ViewGroup.java:5156)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:573)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:508)
	at android.view.View.layout(View.java:15992)
	at android.view.ViewGroup.layout(ViewGroup.java:5156)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
	at android.view.View.layout(View.java:15992)
	at android.view.ViewGroup.layout(ViewGroup.java:5156)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:573)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:508)
	at android.view.View.layout(View.java:15992)
	at android.view.ViewGroup.layout(ViewGroup.java:5156)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
	at android.view.View.layout(View.java:15992)
	at android.view.ViewGroup.layout(ViewGroup.java:5156)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:573)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:508)
	at android.view.View.layout(View.java:15992)
	at android.view.ViewGroup.layout(ViewGroup.java:5156)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
	at android.view.View.layout(View.java:15992)
	at android.view.ViewGroup.layout(ViewGroup.java:5156)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:573)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:508)
	at android.view.View.layout(View.java:15992)
	at android.view.ViewGroup.layout(ViewGroup.java:5156)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
	at android.view.View.layout(View.java:15992)
	at android.view.ViewGroup.layout(ViewGroup.java:5156)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:573)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:508)
	at android.view.View.layout(View.java:15992)
	at android.view.ViewGroup.layout(ViewGroup.java:5156)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2101)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1855)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1062)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5873)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
	at android.view.Choreographer.doCallbacks(Choreographer.java:580)
	at android.view.Choreographer.doFrame(Choreographer.java:550)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5536)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1397)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1192)
Caused by: java.lang.NumberFormatException: Invalid float: "1.34.56"
	at java.lang.StringToReal.invalidReal(StringToReal.java:63)
	at java.lang.StringToReal.initialParse(StringToReal.java:160)
	at java.lang.StringToReal.parseFloat(StringToReal.java:323)
	at java.lang.Float.parseFloat(Float.java:306)
	at android.util.PathParser.getFloats(PathParser.java:178)
	at android.util.PathParser.createNodesFromPathData(PathParser.java:59)
	at android.graphics.drawable.VectorDrawable$VFullPath.updateStateFromTypedArray(VectorDrawable.java:1439)
	at android.graphics.drawable.VectorDrawable$VFullPath.inflate(VectorDrawable.java:1421)
	at android.graphics.drawable.VectorDrawable.inflateInternal(VectorDrawable.java:542)
	at android.graphics.drawable.VectorDrawable.inflate(VectorDrawable.java:458)
	at android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java:1095)
	at android.graphics.drawable.Drawable.createFromXml(Drawable.java:1017)
	at android.content.res.Resources.loadDrawableForCookie(Resources.java:2880)
	... 79 more

**Comment by kiss-dev** [comment] 2019-02-07 08:39
Same problem on ZimLX installed from F-Droid repo
`
Build version: 0.4.4 
Build date: 1980-01-01 00:00:00 
Current date: 2019-02-07 09:20:16 
Device: LGE LG-H525n 
 
Stack trace:  
android.content.res.Resources$NotFoundException: File res/drawable/ic_style.xml from drawable resource ID #0x7f0800b8
	at android.content.res.Resources.loadDrawableForCookie(Resources.java:2469)
	at android.content.res.Resources.loadDrawable(Resources.java:2371)
	at android.content.res.Resources.getDrawable(Resources.java:771)
	at android.content.Context.getDrawable(Context.java:402)
	at android.support.v4.content.ContextCompat.getDrawable(ContextCompat.java:358)
	at android.support.v7.preference.Preference.onBindViewHolder(Preference.java:591)
	at org.zimmob.zimlx.settings.ui.SubPreference.onBindViewHolder(SubPreference.java:45)
	at android.support.v7.preference.PreferenceGroupAdapter.onBindViewHolder(PreferenceGroupAdapter.java:362)
	at android.support.v7.preference.PreferenceGroupAdapter.onBindViewHolder(PreferenceGroupAdapter.java:43)
	at android.support.v7.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:6508)
	at android.support.v7.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:6541)
	at android.support.v7.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:5484)
	at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5750)
	at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5589)
	at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5585)
	at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2231)
	at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1558)
	at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1518)
	at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:610)
	at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3719)
	at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3436)
	at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3988)
	at android.view.View.layout(View.java:15654)
	at android.view.ViewGroup.layout(ViewGroup.java:4969)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:573)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:508)
	at android.view.View.layout(View.java:15654)
	at android.view.ViewGroup.layout(ViewGroup.java:4969)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1705)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1559)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1468)
	at android.view.View.layout(View.java:15654)
	at android.view.ViewGroup.layout(ViewGroup.java:4969)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:573)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:508)
	at android.view.View.layout(View.java:15654)
	at android.view.ViewGroup.layout(ViewGroup.java:4969)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1705)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1559)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1468)
	at android.view.View.layout(View.java:15654)
	at android.view.ViewGroup.layout(ViewGroup.java:4969)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:573)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:508)
	at android.view.View.layout(View.java:15654)
	at android.view.ViewGroup.layout(ViewGroup.java:4969)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1705)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1559)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1468)
	at android.view.View.layout(View.java:15654)
	at android.view.ViewGroup.layout(ViewGroup.java:4969)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:573)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:508)
	at android.view.View.layout(View.java:15654)
	at android.view.ViewGroup.layout(ViewGroup.java:4969)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1705)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1559)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1468)
	at android.view.View.layout(View.java:15654)
	at android.view.ViewGroup.layout(ViewGroup.java:4969)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:573)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:508)
	at android.view.View.layout(View.java:15654)
	at android.view.ViewGroup.layout(ViewGroup.java:4969)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2102)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1859)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1078)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5885)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
	at android.view.Choreographer.doCallbacks(Choreographer.java:580)
	at android.view.Choreographer.doFrame(Choreographer.java:550)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5376)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:908)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:703)
Caused by: java.lang.NumberFormatException: Invalid float: "1.34.56"
	at java.lang.StringToReal.invalidReal(StringToReal.java:63)
	at java.lang.StringToReal.initialParse(StringToReal.java:160)
	at java.lang.StringToReal.parseFloat(StringToReal.java:323)
	at java.lang.Float.parseFloat(Float.java:306)
	at android.util.PathParser.getFloats(PathParser.java:178)
	at android.util.PathParser.createNodesFromPathData(PathParser.java:59)
	at android.graphics.drawable.VectorDrawable$VFullPath.updateStateFromTypedArray(VectorDrawable.java:1439)
	at android.graphics.drawable.VectorDrawable$VFullPath.inflate(VectorDrawable.java:1421)
	at android.graphics.drawable.VectorDrawable.inflateInternal(VectorDrawable.java:542)
	at android.graphics.drawable.VectorDrawable.inflate(VectorDrawable.java:458)
	at android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java:1095)
	at android.graphics.drawable.Drawable.createFromXml(Drawable.java:1017)
	at android.content.res.Resources.loadDrawableForCookie(Resources.java:2459)
	... 79 more
`

**Comment by jerryn70** [comment] 2019-02-26 16:22
Same issue on my galaxy s4 GTI9500
Lollipop

**Comment by otakuhqz** [comment] 2019-03-06 03:56
Fixed in v0.5.1

**Closed by otakuhqz** 2019-03-06 03:56 UTC
